const STATUS_IDLE = 'IDLE'
const STATUS_GETTING_DELIVERY_COST = 'GETTING_DELIVERY_COST'
const STATUS_LOADING = 'LOADING'
const STATUS_ERROR = 'ERROR'
const STATUS_READY = 'READY'
const STATUS_OK = 'OK'

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_CLEAR_TOKEN = 'AUTH_CLEAR_TOKEN'

export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED'
export const PRODUCTS_NOT_LOADED = 'PRODUCTS_NOT_LOADED'

export const ORDER_CLEAR_CART = 'ORDER_CLEAR_CART'
export const ORDER_UPDATE_CART = 'ORDER_UPDATE_CART'
export const ORDER_UPDATE_DETAILS = 'ORDER_UPDATE_DETAILS'
export const ORDER_GET_DELIVERY_COST = 'ORDER_GET_DELIVERY_COST'
export const ORDER_GOT_DELIVERY_COST = 'ORDER_GOT_DELIVERY_COST'
export const ORDER_LOADING = 'ORDER_LOADING'
export const ORDER_NOT_SENT = 'ORDER_NOT_SENT'
export const ORDER_SENT = 'ORDER_SENT'

export const PRODUCTS = {
  STATUS_IDLE,
  STATUS_LOADING,
  STATUS_ERROR,
  STATUS_OK,
  STATUSES: [STATUS_IDLE, STATUS_LOADING, STATUS_ERROR, STATUS_OK],
}

export const ORDER = {
  STATUS_IDLE,
  STATUS_GETTING_DELIVERY_COST,
  STATUS_READY,
  STATUS_LOADING,
  STATUS_ERROR,
  STATUS_OK,
  STATUSES: [STATUS_IDLE, STATUS_GETTING_DELIVERY_COST, STATUS_READY, STATUS_LOADING, STATUS_ERROR, STATUS_OK],
}
